"""<added created and updated date>

Revision ID: 39bcddf3c9a2
Revises: 787b337c037a
Create Date: 2024-01-18 14:38:55.425957

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '39bcddf3c9a2'
down_revision = '787b337c037a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
