"""<your message>

Revision ID: 687762be1bb1
Revises: 945b31bcb73f
Create Date: 2024-01-18 14:17:17.204885

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '687762be1bb1'
down_revision = '945b31bcb73f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.alter_column('body',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('username',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('updated_at',
               existing_type=sa.DATETIME(),
               nullable=True)
        batch_op.drop_column('created_at')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.VARCHAR(), nullable=False))
        batch_op.alter_column('updated_at',
               existing_type=sa.DATETIME(),
               nullable=False)
        batch_op.alter_column('username',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('body',
               existing_type=sa.VARCHAR(),
               nullable=False)

    # ### end Alembic commands ###
